# 2019.03.13 TIL 

추후 에러가 발생할 때 에러를 캐치하기 위해 에러 바운더리를 추가하는 작업을 하였다. 

# Error Boundaries React

과거에, 컴포넌트 내부의 자바스크립트 에러로 인해 리액트 상태가 손상되어 다음 렌더에 cryptic error가 발생하였다. 이 에러는 항상 코드의 이전 오류로 인해 발생하였습니다. 그러나 리액트는 컴포넌트 안에서 해결할 방법을 제공하지 않았고 복구할 수 없었습니다.

## introducing Error Boundaries

UI일부 자바스크립트 에러로 인해 전체 앱이 깨지지 않아야 합ㄴ디ㅏ. 이 문제를 풀기위해, React 16은 'error boundary'개념을 소개합니다.

에러 바운더리는 리액트 컴포넌트로서 자식 컴포넌트 트리에 어디에서나 자바스크립트 오류를 캐치하고 이러한 오류를 기록하며 오류가 발생한 컴포넌트 트리 대신 폴백 UI를 표시합니다.

> Note
> 에러바운더리는 다음과 같은 에러를 캐치하지 않습니다.
>
> - Event Handler
> - Asynchronous code(setTimeout or requestAnimationFrame callback)
> - Server side rendering
> - Error thrown in the error boundary itself

클래식 컴포넌트는 라이프사이클 메서드 `static getDerivedStateFromError()`나 `componentDidCatch()`둘 중 하나 혹은 둘 다 정의하면 에러 바운더리가 됩니다.
오류가 발생하면 `static getDerivedStateFromError()`를 사용하여 폴백 UI를 렌더합니다. `componentDidCatch()`를 사용하여 에러 정보를 로그합니다.

```js
class ErrorBoundary extends React.Component {
  constructor(props) {
    super(props);
    this.state = { hasError: false };
  }

  static getDerivedStateFromError(error) {
    // Update state so the next render will show the fallback UI.
    return { hasError: true };
  }

  componentDidCatch(error, info) {
    // You can also log the error to an error reporting service
    logErrorToMyService(error, info);
  }

  render() {
    if (this.state.hasError) {
      // You can render any custom fallback UI
      return <h1>Something went wrong.</h1>;
    }

    return this.props.children;
  }
}
```

레귤러 컴포넌트처럼 사용할 수 있습니다.

```js
<ErrorBoundary>
  <MyWidget />
</ErrorBoundary>
```

에러바운더리는 자바스크립트의 `cath{}`블록처럼 작동합니다. 컴포넌트는 작동하지 않습니다. 오직 클래스 컴포넌트만 에러 바운더리가 될 수 있습니다. 실제로, 에러 바운더리 컴포넌트를 한 번 선언하고 전체 애플리케이션에서 쓰려고 할 것 입니다.

에러 바운더리는 트리 아래에 있는 컴포넌트 오류만 캐치합니다.
에러 바운더리는 그 자체의 오류를 잡을 수 없습니다.
에러바운더리가 에러 메시지를 렌더하는 데 실패하면, 에러는 가장 가까운 에러바운더리 위로 전파됩니다. 이것은 자바스크립트 `carth{}`블록이 작동하는 방식과 유사합니다.

## Where to Place Error Boundaries

에러 바운더리를 쪼개는 것은 당신에게 달려있습니다. 서버측 프레임워크가 종종 충돌을 처리하는 것처럼 'somethig went wrong' 메시지를 표시하려면 최상위 경로에 컴포넌트를 래핑할 수 있습니다. 
각각 위젯을 래핑할 수 있습니다. 어플리케이션의 나머지와 충돌하지 않도록.

## New Behavior for Uncaught Errors 

이 변화는 중요한 의미를 갖습니다. react 16부터는 에러바운더리에서 캐치되지 않은 오류로 인해 전체 리액트 컴포넌트 트리가 언마운트됩니다. 

16부터 드러나지 않았던 어플리케이션 에러들을 캐치할 수 있게 됩니다. 에러 바운더리를 추가하면 에러가 발생하였을 때 더 나은 사용자 경험을 제공할 수 있습니다. 

## component Stack Trace 

react16은 렌더링하는 동안의 모든 에러를 출력합니다. 앱이 뜻하지 않게 삼킨 것들도 마찬가지입니다. 오류 메시지와 자바스크립트 스택 외에도 컴포넌트 스택 추적을 제공합니다. 컴포넌트 트리에서 발생한 에러를 정확히 볼 수 있습니다. 

또한 component stack trace에서 파일네임과 라인 넘버를 볼 수 있습니다.  create-react-app에서 디폴트로 동작합니다. 
create-react-app을 사용하지 않는다면, [이 플러그인](https://www.npmjs.com/package/babel-plugin-transform-react-jsx-source)을 사용할 수 있습니다. 


## How About try/catch? 

try/catch는 훌륭하지만 명령형 코드에서만 동작합니다. 

```js
try {
  showButton()
}catch(error) {
//...
}
```

그러나, 리액트 컴포넌트는 선언적이며 렌더링 대상을 지정합니다. 
에러 바운더리는 리액트의 선언적 특성을 보전하고 당신이 예상한대로 동작합니다. 예를들어, 트리의 깊숙한 어느곳에서 setState에 의해 발생한 componentDidUpdate() 메서드로 에러가 발생해도, 가장 가까운 에러 바운더리에 올바르게 전파됩니다. 

## How About Event Handlers? 

에러 바운더리는 이벤트 핸들러 안에 있는 에러를 캐치하지 않습니다.
리액트는 이벤트 핸들러의 에러를 복구하기 위해 에러 바운더리를 필요하지 않습니다. 라이프 사이클및 렌더 메서드와 달리 이벤트 핸들러는 렌더링할 때 에러가 발생하지 않습니다. 그래서, 그들이 쓰로우하면 리액트는 여전히 화면에 무엇을 표시할지 압니다. 

만약 이벤트 핸들러안의 에러를 캐치해야 한다면, 자바스크립트의 try/catch 구문을 사용하세요. 

```js
class MyComponent extends React.Component {
  constructor(props) {
    super(props);
    this.state = { error: null };
    this.handleClick = this.handleClick.bind(this);
  }

  handleClick() {
    try {
      // Do something that could throw
    } catch (error) {
      this.setState({ error });
    }
  }

  render() {
    if (this.state.error) {
      return <h1>Caught an error.</h1>
    }
    return <div onClick={this.handleClick}>Click Me</div>
  }
}
```

